variables:
  IMAGE_TAG: '$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA'

stages:
  - build
  - test
  - deploy-dev
  - deploy-staging
  - clean-up
  - roll-back

build:
  stage: build
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS $CI_REGISTRY
  script:
    - docker-compose build
    - docker image tag $PROJECT_NAME:$IMAGE_TAG $CI_REGISTRY/$PROJECT_NAME:$IMAGE_TAG
    - docker push $CI_REGISTRY/$PROJECT_NAME:$IMAGE_TAG
    - docker rmi $PROJECT_NAME:$IMAGE_TAG $CI_REGISTRY/$PROJECT_NAME:$IMAGE_TAG
  cache:
    key: '$CI_COMMIT_REF_NAME'
    paths:
      - node_modules/
  rules:
    - if: ($CI_COMMIT_REF_NAME == "develop" || $CI_COMMIT_REF_NAME == "staging")

deploy-dev:
  stage: deploy-dev
  script:
    - |
      cat << EOF > deploy.sh
      #!/bin/sh
      docker pull $CI_REGISTRY/$PROJECT_NAME:$IMAGE_TAG
      docker rm -f $PROJECT_NAME
      docker run --restart unless-stopped --name=$PROJECT_NAME -dp $PORT_APP:80 -v /home/projects/qldp/convert/pdf/:/var/www/download/ $CI_REGISTRY/$PROJECT_NAME:$IMAGE_TAG
      EOF
    - chmod +x deploy.sh
    - scp deploy.sh $SSH_USER@$SERVER_DEV:~/deploy.sh
    - ssh $SSH_USER@$SERVER_DEV "docker login -u $REGISTRY_USER -p $REGISTRY_PASS $CI_REGISTRY && chmod +x ~/deploy.sh && ~/deploy.sh && rm -rf ~/deploy.sh"
  rules:
    - if: ($CI_COMMIT_REF_NAME == "develop")

deploy-staging:
  stage: deploy-staging
  script:
    - |
      cat << EOF > deploy.sh
      #!/bin/sh
      docker pull $CI_REGISTRY/$PROJECT_NAME:$IMAGE_TAG
      docker rm -f $PROJECT_NAME
      docker run --restart unless-stopped --name=$PROJECT_NAME -dp $PORT_API:80 -v /home/projects/qldp/convert/pdf/:/var/www/download/ $CI_REGISTRY/$PROJECT_NAME:$IMAGE_TAG
      EOF
    - chmod +x deploy.sh
    - scp deploy.sh $SSH_USER@$SERVER_STAGING:~/deploy.sh
    - ssh $SSH_USER@$SERVER_STAGING "docker login -u $REGISTRY_USER -p $REGISTRY_PASS $CI_REGISTRY && chmod +x ~/deploy.sh && ~/deploy.sh && rm -rf ~/deploy.sh"
  rules:
    - if: ($CI_COMMIT_REF_NAME == "staging")

clean-up:
  stage: clean-up
  script:
    - cd $PATH_REGISTRY_PROJECT && ls -lt | grep "$CI_COMMIT_REF_NAME-*" | tail -n +4 | awk '{print $NF}' | xargs -I {} rm -rf {}
    - |
      cat << EOF > checkImages.sh
      #!/bin/bash
      docker images $CI_REGISTRY/$PROJECT_NAME:$CI_COMMIT_REF_NAME-* --format '{{.Repository}}:{{.Tag}} {{.CreatedAt}}' | sort -k 2 -r | awk 'NR>2{print $1}' | xargs -r docker rmi
      echo "clean up done."
      EOF
    - chmod +x checkImages.sh
    - scp checkImages.sh $SSH_USER@$SERVER_DEV:~/checkImages.sh
    - ssh $SSH_USER@$SERVER_DEV "chmod +x ~/checkImages.sh && ~/checkImages.sh && rm -rf ~/checkImages.sh"
  rules:
    - if: ($CI_COMMIT_REF_NAME == "develop" || $CI_COMMIT_REF_NAME == "staging")
#roll-back-fail:
#  stage: roll-back
#  script:
#    - cd $PATH_REGISTRY_PROJECT && rm -f $IMAGE_TAG
#  rules:
#    - if: ($CI_COMMIT_REF_NAME == "develop" || $CI_COMMIT_REF_NAME == "staging")
#    - when: on_failure
